-- https://github.com/utilyre/barbecue.nvim

if true then
  return {}
end

return {
  "utilyre/barbecue.nvim",
  event = "LazyFile",
  name = "barbecue",
  version = "*",
  dependencies = {
    "SmiteshP/nvim-navic",
    -- "nvim-tree/nvim-web-devicons",
  },
  opts = {
    ---Whether to replace file icon with the modified symbol when buffer is
    ---modified.
    ---
    ---@type boolean
    show_modified = true,
    theme = {
      modified = { fg = require("tokyonight.colors").green },
    },
    -- kinds = {
    --   File = "",
    --   Module = "",
    --   Namespace = "",
    --   Package = "",
    --   Class = "",
    --   Method = "",
    --   Property = "",
    --   Field = "",
    --   Constructor = "",
    --   Enum = "",
    --   Interface = "",
    --   Function = "",
    --   Variable = "",
    --   Constant = "",
    --   String = "",
    --   Number = "",
    --   Boolean = "",
    --   Array = "",
    --   Object = "",
    --   Key = "",
    --   Null = "",
    --   EnumMember = "",
    --   Struct = "",
    --   Event = "",
    --   Operator = "",
    --   TypeParameter = "",
    -- },
    -- kinds = require("lazyvim.config").icons.kinds,
    -- kinds = require("mini.icons").mock_nvim_web_devicons(),
    kinds = {
      Array = "",
      Boolean = "󰨙",
      Class = "",
      Codeium = "󰘦",
      Color = "",
      Control = "",
      Collapsed = "",
      Constant = "󰏿",
      Constructor = "",
      Copilot = "",
      Enum = "",
      EnumMember = "",
      Event = "",
      Field = "",
      File = "",
      Folder = "",
      Function = "󰊕",
      Interface = "",
      Key = "",
      Keyword = "",
      Method = "󰊕",
      Module = "",
      Namespace = "󰦮",
      Null = "",
      Number = "󰎠",
      Object = "",
      Operator = "",
      Package = "",
      Property = "",
      Reference = "",
      Snippet = "",
      String = "",
      Struct = "󰆼",
      TabNine = "󰏚",
      Text = "",
      TypeParameter = "",
      Unit = "",
      Value = "",
      Variable = "󰀫",
    },
  },
}
