-- Full spec: https://www.lazyvim.org/plugins/colorscheme

return {
  {
    "folke/tokyonight.nvim",
    opts = function()
      -- local bg_color = "#1a1b26"
      -- vim.cmd [[hi Normal ctermbg=none guibg=none]]
      -- vim.cmd [[hi SignColumn ctermbg=none guibg=none]]
      -- vim.cmd [[hi NormalNC ctermbg=none guibg=none]]
      -- vim.cmd [[hi MsgArea ctermbg=none guibg=none]]
      -- vim.cmd [[hi TelescopeBorder ctermbg=none guibg=none]]
      -- vim.cmd [[hi NvimTreeNormal ctermbg=none guibg=none]]
      -- vim.cmd [[let &fcs='eob: ']]
      -- vim.cmd [[hi NormalFloat ctermbg=none guibg=bg_color]]
      -- vim.cmd [[hi CmpMenu ctermbg=none guibg=bg_color]]
      -- vim.cmd [[hi CmpItemMenu ctermbg=none guibg=bg_color]]
      -- vim.cmd [[hi CmpDocumentation ctermbg=none guibg=bg_color]]
      -- vim.cmd [[hi link CmpMenu NormalFloat]]
      -- vim.cmd [[hi link CmpItemMenu NormalFloat]]
      -- vim.cmd [[hi link CmpDocumentation NormalFloat]]
      -- vim.cmd [[hi FloatShadow ctermbg=none guibg=bg_color]]
      -- vim.cmd [[hi FloatShadowThrough ctermbg=none guibg=bg_color]]
      -- vim.cmd [[hi NoiceMini ctermbg=none guibg=bg_color]]
      -- vim.cmd [[autocmd! ColorScheme * highlight NoiceMini guibg=bg_color]]

      -- TODO: figure out why this doesn't work
      -- local colors = require("tokyonight.colors").setup()
      -- vim.cmd [[hi IndentBlanklineContextChar guifg=colors.fg]]
      return {
        style = "night",
        transparent = true,
        styles = {
          sidebars = "transparent",
          floats = "transparent",
        },
        -- TODO: add Lunarvim icons?
        -- icons = {},
      }
    end,
  },

  -- {
  --   "LunarVim/lunar.nvim",
  --   -- lazy = false, -- make sure we load this during startup if it is your main colorscheme
  --   -- priority = 1000, -- make sure to load this before all the other start plugins
  --   config = function()
  --     vim.cmd.colorscheme "lunar"
  --
  --     -- vim.api.nvim_create_autocmd("ColorScheme", {
  --     --   pattern = "*",
  --     --   callback = function()
  --     --     local hl_groups = {
  --     --       "Normal",
  --     --       "SignColumn",
  --     --       "NormalNC",
  --     --       "TelescopeBorder",
  --     --       "NvimTreeNormal",
  --     --       "NvimTreeNormalNC",
  --     --       "EndOfBuffer",
  --     --       "MsgArea",
  --     --     }
  --     --     for _, name in ipairs(hl_groups) do
  --     --       vim.cmd(string.format("highlight %s ctermbg=none guibg=none", name))
  --     --     end
  --     --   end,
  --     -- })
  --     -- vim.opt.fillchars = "eob: "
  --
  --     -- vim.cmd [[au ColorScheme * hi Normal ctermbg=none guibg=none]]
  --     -- vim.cmd [[au ColorScheme * hi SignColumn ctermbg=none guibg=none]]
  --     -- vim.cmd [[au ColorScheme * hi NormalNC ctermbg=none guibg=none]]
  --     -- vim.cmd [[au ColorScheme * hi MsgArea ctermbg=none guibg=none]]
  --     -- vim.cmd [[au ColorScheme * hi TelescopeBorder ctermbg=none guibg=none]]
  --     -- vim.cmd [[au ColorScheme * hi NvimTreeNormal ctermbg=none guibg=none]]
  --     -- vim.cmd [[let &fcs='eob: ']]
  --
  --     -- -- lunar theme specific
  --     -- local bg_color = "#1a1b26"
  --     -- vim.cmd [[au ColorScheme * hi NvimTreeWinSeparator ctermbg=none guibg=bg_color]]
  --     -- vim.cmd [[au ColorScheme * hi TabLineFill ctermbg=none guibg=bg_color]]
  --     -- vim.cmd [[au ColorScheme * hi VertSplit ctermbg=none guibg=bg_color]]
  --     -- vim.cmd [[au ColorScheme * hi FloatBorder ctermbg=none guibg=bg_color]]
  --     -- vim.cmd [[au ColorScheme * hi NormalFloat ctermbg=none guibg=bg_color]]
  --     -- vim.cmd [[au ColorScheme * hi WhichKeyFloat ctermbg=none guibg=bg_color]]
  --     -- vim.cmd [[au ColorScheme * hi WhichKeyFloat ctermbg=none guibg=bg_color]]
  --     -- vim.cmd [[au ColorScheme * hi TelescopeNormal ctermbg=none guibg=bg_color]]
  --     -- vim.cmd [[au ColorScheme * hi Folded ctermbg=none guibg=bg_color]]
  --     -- vim.cmd [[au ColorScheme * hi DiagnosticVirtualTextOk ctermbg=none guibg=bg_color]]
  --     -- vim.cmd [[au ColorScheme * hi DiagnosticVirtualTextHint ctermbg=none guibg=bg_color]]
  --     -- vim.cmd [[au ColorScheme * hi DiagnosticVirtualTextInfo ctermbg=none guibg=bg_color]]
  --     -- vim.cmd [[au ColorScheme * hi DiagnosticVirtualTextWarn ctermbg=none guibg=bg_color]]
  --     -- vim.cmd [[au ColorScheme * hi DiagnosticVirtualTextError ctermbg=none guibg=bg_color]]
  --
  --     vim.cmd [[hi Normal ctermbg=none guibg=none]]
  --     vim.cmd [[hi SignColumn ctermbg=none guibg=none]]
  --     vim.cmd [[hi NormalNC ctermbg=none guibg=none]]
  --     vim.cmd [[hi MsgArea ctermbg=none guibg=none]]
  --     vim.cmd [[hi TelescopeBorder ctermbg=none guibg=none]]
  --     vim.cmd [[hi NvimTreeNormal ctermbg=none guibg=none]]
  --     vim.cmd [[let &fcs='eob: ']]
  --
  --     -- lunar theme specific
  --     local bg_color = "#1a1b26"
  --     vim.cmd [[hi NvimTreeWinSeparator ctermbg=none guibg=bg_color]]
  --     vim.cmd [[hi TabLineFill ctermbg=none guibg=bg_color]]
  --     vim.cmd [[hi VertSplit ctermbg=none guibg=bg_color]]
  --     vim.cmd [[hi FloatBorder ctermbg=none guibg=bg_color]]
  --     vim.cmd [[hi NormalFloat ctermbg=none guibg=bg_color]]
  --     vim.cmd [[hi WhichKeyFloat ctermbg=none guibg=bg_color]]
  --     vim.cmd [[hi WhichKeyFloat ctermbg=none guibg=bg_color]]
  --     vim.cmd [[hi TelescopeNormal ctermbg=none guibg=bg_color]]
  --     vim.cmd [[hi Folded ctermbg=none guibg=bg_color]]
  --     vim.cmd [[hi DiagnosticVirtualTextOk ctermbg=none guibg=bg_color]]
  --     vim.cmd [[hi DiagnosticVirtualTextHint ctermbg=none guibg=bg_color]]
  --     vim.cmd [[hi DiagnosticVirtualTextInfo ctermbg=none guibg=bg_color]]
  --     vim.cmd [[hi DiagnosticVirtualTextWarn ctermbg=none guibg=bg_color]]
  --     vim.cmd [[hi DiagnosticVirtualTextError ctermbg=none guibg=bg_color]]
  --     -- vim.cmd [[hi CmpDocumentation ctermbg=none guibg=bg_color]]
  --     -- vim.cmd [[hi CmpItemMenu ctermbg=none guibg=bg_color]]
  --   end,
  -- },

  -- {
  --   "catppuccin/nvim",
  --   name = "catppuccin",
  --   lazy = false,
  --   priority = 1000,
  --   config = function()
  --     local transparent = true
  --
  --     require("catppuccin").setup {
  --       flavour = transparent and "mocha" or "macchiato",
  --       transparent_background = transparent,
  --       styles = {
  --         keywords = { "bold" },
  --         functions = { "italic" },
  --       },
  --       integrations = {
  --         alpha = false,
  --         neogit = false,
  --         nvimtree = false,
  --         illuminate = false,
  --         rainbow_delimiters = false,
  --         dropbar = { enabled = false },
  --         mason = true,
  --         noice = true,
  --         notify = true,
  --         neotree = true,
  --         neotest = true,
  --         which_key = true,
  --         telescope = { style = transparent and nil or "nvchad" },
  --       },
  --       custom_highlights = function(colors)
  --         return {
  --           -- custom
  --           PanelHeading = {
  --             fg = colors.lavender,
  --             bg = transparent and colors.none or colors.crust,
  --             style = { "bold", "italic" },
  --           },
  --
  --           -- lazy.nvim
  --           LazyH1 = {
  --             bg = transparent and colors.none or colors.peach,
  --             fg = transparent and colors.lavender or colors.base,
  --             style = { "bold" },
  --           },
  --           LazyButton = {
  --             bg = colors.none,
  --             fg = transparent and colors.overlay0 or colors.subtext0,
  --           },
  --           LazyButtonActive = {
  --             bg = transparent and colors.none or colors.overlay1,
  --             fg = transparent and colors.lavender or colors.base,
  --             style = { "bold" },
  --           },
  --           LazySpecial = { fg = colors.green },
  --
  --           CmpItemMenu = { fg = colors.subtext1 },
  --           MiniIndentscopeSymbol = { fg = colors.overlay0 },
  --
  --           FloatBorder = {
  --             fg = transparent and colors.blue or colors.mantle,
  --             bg = transparent and colors.none or colors.mantle,
  --           },
  --
  --           FloatTitle = {
  --             fg = transparent and colors.lavender or colors.base,
  --             bg = transparent and colors.none or colors.lavender,
  --           },
  --         }
  --       end,
  --       color_overrides = {
  --         mocha = {
  --           red = "#f07c82",
  --           blue = "#70a1ff",
  --           green = "#7bed9f",
  --           yellow = "#ffeaa7",
  --
  --           sky = "#5ef1ff",
  --           pink = "#ffacfc",
  --           peach = "#ffbe76",
  --         },
  --       },
  --     }
  --     -- vim.cmd.colorscheme "catppuccin"
  --     -- local palette = require("catppuccin.palettes").get_palette()
  --     -- require("mvim.config").filling_pigments(palette)
  --   end,
  -- },
}
